# Book settings
title:
author: The Notre Dame Artifical Intelligence and Machine Learning & Modeling Team
logo: docs/images/logo.png
only_build_toc_files: false

repository:
  url: https://github.com/starlight-traveler/nd-aimm-main-computer/
  branch: main

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://starlight-traveler.github.io/nd-aimm-main-computer/
  extra_footer: |
    <div>
        <b>All content (unless otherwise specified) is subject to the <a href="https://www.mozilla.org/en-US/MPL">MIT License.</a></b>
    </div>
  favicon: docs/images/favicon.ico

#######################################################################################
# Execution settings
execute:
  execute_notebooks: off

#######################################################################################
# Bibliography settings
bibtex_bibfiles:
  - docs/bibliography.bib

#######################################################################################
# Sphinx settings
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"
